/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LjProduct {
        "changeCart": (price: number) => void;
        "description": string;
        "image": string;
        "name": string;
        "price": number;
    }
    interface LjRoot {
    }
}
declare global {
    interface HTMLLjProductElement extends Components.LjProduct, HTMLStencilElement {
    }
    var HTMLLjProductElement: {
        prototype: HTMLLjProductElement;
        new (): HTMLLjProductElement;
    };
    interface HTMLLjRootElement extends Components.LjRoot, HTMLStencilElement {
    }
    var HTMLLjRootElement: {
        prototype: HTMLLjRootElement;
        new (): HTMLLjRootElement;
    };
    interface HTMLElementTagNameMap {
        "lj-product": HTMLLjProductElement;
        "lj-root": HTMLLjRootElement;
    }
}
declare namespace LocalJSX {
    interface LjProduct {
        "changeCart"?: (price: number) => void;
        "description"?: string;
        "image"?: string;
        "name"?: string;
        "price"?: number;
    }
    interface LjRoot {
    }
    interface IntrinsicElements {
        "lj-product": LjProduct;
        "lj-root": LjRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lj-product": LocalJSX.LjProduct & JSXBase.HTMLAttributes<HTMLLjProductElement>;
            "lj-root": LocalJSX.LjRoot & JSXBase.HTMLAttributes<HTMLLjRootElement>;
        }
    }
}
